### ISSUE TITLE
[BUG?] Error 403 Forbidden

### ISSUE THREAD

**Issue by wes1993** [satheshshiva/CorporateMail#1]
Hello,
Thanks for your work :-D

When I try to add and outlook WORK account a 403 error is coming, I have used this URL: http://mail.office365.com/

**Comment by satheshshiva** [comment]
Are you using the right credentials? Or your company might be blocking the internet access.

**Comment by wes1993** [comment]
Hello @satheshshiva,
Thanks a lot for you reply!! Yes the credentials are correct.

No but when I use Outlook from browser Microsoft Website redirect to another website and I need to insert an OTP code, probably your app won't handle this?

Best Regards
Stefano

**Comment by satheshshiva** [comment]
No, OTP is not supported. Sorry about that.

**Comment by wes1993** [comment]
Ok thanks a lot
